### PR TITLE
More details (stacktrace) for the caller

### PR DESCRIPTION
**Pull request by kdriedger-simutech**
When the caller was getting an exception back from the callee, it was confusing where the exception was being throw. Adding the stack trace to the details of the reject message would be helpful for tracing the source of the error.

### CODE REVIEW

**Comment by darkl** [comment]
A bit vulnerable, wouldn't you say?

**Comment by kdriedger-simutech** [comment]
Yeah, hmm… perhaps, needs to be protected by a Debug Build/Deployed Build flag.  Not sure if you have something like that.

**Comment by darkl** [comment]
Perhaps the appropriate place to set such a flag is in an ICalleeRegistrationInterceptor instance.
I guess there should be a method there which returns a new "RpcEndpointOptions" instance which one of its properties indicates whether to include the exception's stack trace. Also, I find it more appropriate to include the stacktrace as a separated property (perhaps in the keywordArguments dictionary), than as text included with the error message.

Elad

**Comment by darkl** [comment]
See the rpc-settings branch. This needs some work though.

Elad

**Comment by kdriedger-simutech** [comment]
Yeah, hmm… perhaps, needs to be protected by a Debug Build/Deployed Build flag.  Not sure if you have something like that.

**Comment by kdriedger-simutech** [comment]
Will do, Elad.


Based on reading you’re blog on Typed WAMP, I followed the links, and they were mentioning that the reflection API could be hidden behind some security.  Do you know if that was the implementation or was it just a planning idea?

Perhaps the full stacktrace could use/reuse this mechanism?  I do like the direction that you’ve suggested.

If I understand correctly the call to RegisterCallee would take a custom concrete implementation of  ICalleeRegistrationInterceptor that returns a new CalleeSettings object with the  IncludeExceptionStackTrace set to true.



I felt the same pain as you on the calling conventions for WAMP.  I made a proxy as well but for regular javascript.  Which means my call sites can look like regular method calls.  (performance is worse, I may have to consider making my API less chatty or convert over to MsgPack).

Kevin

**Comment by darkl** [comment]
Hi Kevin,

AFAIK reflection hasn't been implemented yet and its spec is only a draft.

Regarding authentication: that indeed may be a possibility: a client could try to authenticate as "debug" or something like that and then we could check that the client indeed has the "debug" role in the code casting the exception.

Elad

**Pull request closed without merging**
