### PR TITLE
Aspnet transform

### PR DESCRIPTION
**Pull request by kasravi**
### asp.net transform

route would be defined like this:

```
    [Route("path/to/endpoint")]
    public class MyRouterController : AspNetWebsocketTransform.RouterController
    {
    }
```
and usage is just like all other transforms:
```
    var host = new WampHost();
            host.RegisterTransport(new AspNetWebsocketTransform(),
                new  JTokenJsonBinding());
```

### CODE REVIEW

**Comment by darkl** [comment]
Can you please explain where do you write the WampHost lines in your ASP.NET application?

**Comment by kasravi** [comment]
in my case since we are using DI, I'm injecting that as a service. ([define](https://github.com/Orckestra/CMS-Foundation/blob/feature-wamp/Composite/Core/WebClient/Services/WampRouter/WampRouter.cs) and [add](https://github.com/Orckestra/CMS-Foundation/blob/feature-wamp/Composite/Core/WebClient/Services/WampRouter/WampRouterResolverRegistry.cs))
but you can also place them in Global.asax to be ran on startup

**Comment by darkl** [comment]
Is it possible to get the transport injected as well instead of holding it in a static variable?

**Comment by kasravi** [comment]
The problem is the api controller is static, and therefor I made the instance static. I didn't investigate enough since we are using a single router and I didn't find the need. but maybe I could search more.

**Comment by darkl** [comment]
@kasravi, I took a look on how ASP.NET is mixed with SignalR. I found [this tutorial](https://www.asp.net/signalr/overview/getting-started/tutorial-getting-started-with-signalr-and-mvc). What do you think about this approach? We already have an Owin transport.

Elad

**Comment by darkl** [comment]
I successfully created a new ASP.NET MVC application and modified the Startup.cs to this file:

```csharp
using Microsoft.Owin;
using Owin;
using WampSharp.Binding;
using WampSharp.Owin;
using WampSharp.V2;

[assembly: OwinStartupAttribute(typeof(WebApplication1.Startup))]
namespace WebApplication1
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);

            WampHost host = new WampHost();

            host.RegisterTransport(new OwinWebSocketTransport(app),
                                   new JTokenJsonBinding());

            host.Open();
        }
    }
}
```

I had to update the installed Microsoft.CodeDom.Providers.DotNetCompilerPlatform package, but it works. It seems cleaner than your approach.

What do you think?

**Comment by kasravi** [comment]
That is indeed cleaner (a lot cleaner), but sadly using Owin is not on the table in our case, because it would add extra dependencies that our users don't really need. This commit is intended for people like us that have the endpoints implemented with new ApiController already and want to grasp wamp without that much change.
As the commit is very similar to ASP.Net core transport I wonder what makes you uncomfortable the most. the static instance, the way I register the route, or something else?

**Comment by darkl** [comment]
I'm mainly worried about the static instance.

Elad

**Comment by kasravi** [comment]
ok let me see if there is other way around

**Comment by kasravi** [comment]
@darkl Changed the ApiController to be injected with the transport.

**Comment by darkl** [comment]
Can you please show the updated setup code?

**Comment by darkl** [comment]
Hi @kasravi,
please look at my aspnet_transform branch. I think I found a way to make things cleaner. (using the classic IHttpHandler interface)

Usage:
```csharp
protected void Application_Start()
{
    WampHost host = new WampHost();

    // Listens at http://localhost:49875/ws
    host.RegisterTransport(new AspNetWebsocketTransport("ws"),
                           new JTokenJsonBinding());

    host.Open();

    // ...
}
```

**Comment by kasravi** [comment]
Aaah sweet! it's a totally cleaner approach. may be not noticing the WebSocketWrapperConnection push me that way. but I like it. thanks @darkl

**Comment by darkl** [comment]
I'll try to merge it this weekend and publish a package to NuGet.

**Comment by kasravi** [comment]
by the way I had set it it up with a service locator like [this](https://github.com/Orckestra/CMS-Foundation/blob/feature-wamp/Composite/Core/WebClient/Services/WampRouter/WampRouter.cs). this way I could have inject the transport when it is needed, but I can see no benefit comparing to this approach.

**Pull request merged**
