### PR TITLE
Correct spelling of occurred in Logs and comments

### PR DESCRIPTION
**Pull request by Minimaximize**

### CODE REVIEW

**Comment by darkl** [comment]
This is embarrassing... Thanks!

**Comment by Minimaximize** [comment]
No worries! 👍

**Comment by Minimaximize** [comment]
(Looks like I've got some build issues with Travis - is there any info on how I might fix that)

**Comment by darkl** [comment]
That build is broken, I'll fix it in the next few months.

Elad

**Comment by darkl** [comment]
Merged into develop. New release expected in September after .NET Core 3.0 is released.

Elad

**Pull request closed without merging**
