### PR TITLE
fix intermittent OperationCancelledException on closing websocket connection

### PR DESCRIPTION
**Pull request by bigbearzhu**
related to #176.

### CODE REVIEW

**Comment by bigbearzhu** [comment]
seems build is broken?

**Comment by darkl** [comment]
Will try to merge this later on this week.
I think we should try to look also at [Owin.WebSocket's while loop](https://github.com/bryceg/Owin.WebSocket/blob/master/src/Owin.WebSocket/WebSocketConnection.cs#L237).

**Comment by bigbearzhu** [comment]
Many thanks for that. It's great. The [Owin.WebSocket's while loop](https://github.com/bryceg/Owin.WebSocket/blob/master/src/Owin.WebSocket/WebSocketConnection.cs#L237) in their `RunWebSocket` looks similar to WampSharp's RunAsync. Howerver, it seems they swallows any error on `mWebSocket.Close`. Not sure whether it is safe enough.

**Comment by darkl** [comment]
After looking at [this comment](https://github.com/NVentimiglia/Websockets.PCL/blob/master/Websockets.Net/WebSocketWrapper.cs#L72) and [googling a bit](http://stackoverflow.com/questions/26744420/net-websocket-closeoutputasync-vs-closeasync), I suspect the problem you are facing is actually due to the fact that we are using CloseAsync and not CloseOutputAsync. What do you think?

**Comment by darkl** [comment]
Please disregard my previous comment as OWIN doesn't have this overload.

**Comment by bigbearzhu** [comment]
Thanks @darkl for the update. How is everything going? We have monitored our memory usage with this change running for about 4 days. So far we didn't see any of those hanging channel or leak. We only saw "A send operation is already in progress." intermittently when server received a close frame and tried to call `CloseAsync`. What do you think about this one? Should we swallow it? I am guessing Microsoft AspNetWebSocket maybe also somehow sending close response to client which caused this conflict.

`"A send operation is already in progress.", Source: "System.Web", StackTrace: "   at System.Web.WebSockets.AspNetWebSocket.ThrowIfSendUnavailable(Boolean allowClosed)\r\n   at System.Web.WebSockets.AspNetWebSocket.CloseOutputAsyncImpl(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken, Boolean performValidation)\r\n   at System.Web.WebSockets.AspNetWebSocket.CloseOutputAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)\r\n   at Microsoft.Owin.Host.SystemWeb.WebSockets.OwinWebSocketWrapper.CloseAsync(Int32 status, String description, CancellationToken cancel)\r\n   at WampSharp.Owin.OwinWebSocketWrapper.CloseAsync(WebSocketCloseStatus closeStatus, String closeDescription, CancellationToken cancel)\r\n   at WampSharp.WebSockets.WebSocketWrapperConnection`1.<RunAsync>d__14.MoveNext() in C:\\git\\WampSharp\\src\\net45\\Extensions\\WampSharp.WebSockets\\WebSockets\\WebSocketWrapperConnection.cs:line 116"`

**Comment by darkl** [comment]
Hi, I am sorry, but I didn't have time yet to check your pull request.
Hopefully on the weekend I'll have some time to review your pull request and read your further research.

Elad

**Comment by darkl** [comment]
Hi @bigbearzhu,
Please check my system-websockets-issue branch. I made some changes to avoid many exceptions. In addition I made changes to the Owin implementation that are based on [this](https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Owin/WebSockets/OwinWebSocketAdapter.cs) code. I found it more appropriate to handle the state of WebSocket in the Owin wrapper class, than in the WebSocketWrapperConnection class.
Another thing I have done is changed the unique id of each connection to be a property that can be written to the log, rather than fixed in the logger name.
Apart from that, I made some code style changes.

Please check if this works for you, and if so, I'll merge it and release a new version.

Elad

**Comment by bigbearzhu** [comment]
Great! Thanks for your effort. The `State` part does look better. Will have a try on our build next week.

**Comment by bigbearzhu** [comment]
Hi @darkl We are still testing this change. Unfortunately, the change I made on my local branch still have the same issue after a few days test. Haven't got a chance to get this pull request build used on the test server yet. I suspect this pull request would probably have the same issue too as no essential changes were made. Still need a bit more time to confirm it.

**Comment by bigbearzhu** [comment]
@darkl I think we can merge the pull request now. We have been running a build with this pull request on internal production server. Haven't seen serious issue for quite a while. Thanks for your help.

**Pull request merged**
